# fly.toml app configuration file generated for crypto-wallet-fragrant-cherry-3610 on 2025-10-25T22:38:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crypto-wallet-fragrant-cherry-3610'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
